### ISSUE TITLE
call decorated verify_password

### ISSUE THREAD

**Issue by yiga2** [miguelgrinberg/Flask-HTTPAuth#101]
Considering
```
    @auth.verify_password
    def authenticate(username, password):
```

We use flask as a proxy to a 3rd party website, and `HTTPBasicAuth()` to capture the credentials to pass on to the logon page and get the cookies (with requests).

Sometimes the target website abruptly closes the connection/session and we need to re-authenticate, which we initially do in `authenticate()`

Is there a way to force for a re-authentication or call `authenticate()` from another function without passing the authenticated password ?

If not, I rather not store the user password in `g` or in flask's `session` but had hoped auth.get_password()` or similar would return it.

**Comment by miguelgrinberg** [comment]
The username and password are already stored in the request object.

- `request.authorization.username`
- `request.authorization.password`

**Comment by yiga2** [comment]
oh, didn't know that ! So a
 `authenticate(request.authorization.username, request.authorization.password)` 
will just do. Thanks !
