### ISSUE TITLE
HTTP Method-based role authentiation

### ISSUE THREAD

**Issue by Querela** [miguelgrinberg/Flask-HTTPAuth#106]
In my REST API webapp, I wanted to provide read-only access as well as read-and-write access using different roles for different HTTP methods, and both protected by HTTPBasicAuth.

My current (working) solution is:
```python
# logging just to trace calls
from functools import wraps

from flask import Blueprint
from flask import current_app
from flask import request

from ..app import auth

bp_api = Blueprint("api", __name__)

def login_required_method_filter(role, methods=None):
    def filter_method_decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            current_app.logger.warning(
                "request? - %s - %s of %s - %s",
                request.endpoint,
                request.method,
                methods,
                role,
            )
            if methods and request.method not in methods:
                # ignore and continue with request
                return None

            f_authd = auth.login_required(role=role)(f)
            return f_authd(*args, **kwargs)

        return decorated_function

    return filter_method_decorator


@bp_api.before_request
@login_required_method_filter(role="api-rw", methods=("POST", "DELETE", "PUT"))
def before_request_rw():
    """Protect write API routes"""
    current_app.logger.warning(
        "before_request_rw - %s - %s", request.endpoint, request.method
    )


@bp_api.before_request
@login_required_method_filter(role="api-ro", methods=("GET", "HEAD", "OPTIONS"))
def before_request_ro():
    """Protect API routes"""
    # user = auth.current_user()
    # roles = user["roles"]
    # if request.method in ("GET", "HEAD") ...
    current_app.logger.warning(
        "before_request_ro - %s - %s", request.endpoint, request.method
    )

# api methods, using MethodViews or MethodResource from flask_apispec
```

```python
# app httpauth configs
"AUTH_USERS": [
    {
        "name": "api-ro",
        "password": generate_password_hash("api-ro"),
        "roles": ["api-ro"],
    },
    {
        "name": "api-rw",
        "password": generate_password_hash("api-rw"),
        "roles": ["api-rw", "api-ro"],
    },
]
```

The idea is that the authentiation with roles only checks if the correct HTTP method is used, else the method is unprotected. But with covering all HTTP methods, one check will work and protect using the given role. So the main issue is when not all HTTP methods are covered with handlers it could potentially let a request through. (`methods=None` is the catch-all to protect against this)

In my tests it works reliably. The only problem for me is currently (in my browser) how to disable old tokens, e. g. if I want to switch between read+write and read-only ...

Maybe this is a use-case that is interesting for others or can even be included into this library.

**Comment by miguelgrinberg** [comment]
The problem with this approach is that I'm not sure it is common to have a distinction between read-only and read-write access solely based on the HTTP method. In general you are going to find that some GET endpoints need to be restricted, and some POST/PUT/DELETE are okay to be used by normal users. To be honest, it seems you would have a simpler implementation if you handled the read-only vs. read-write in a single custom decorator that you attach to a `before_request` instead of having two, which in my opinion makes it more confusing.

**Comment by Querela** [comment]
> The problem with this approach is that I'm not sure it is common to have a distinction between read-only and read-write access solely based on the HTTP method. In general you are going to find that some GET endpoints need to be restricted, and some POST/PUT/DELETE are okay to be used by normal users.

I currently have multiple resource classes with each their own GET, POST, PUT, DELETE methods. Read-only access is ok, write needs to be more restricted. If I need to allow some single resources for writes (like POST, DELETE, ...) then I can't use the `before_request` handler anymore as it would restrict it. That's an obvious minus.
But then I can just repeat the decorator for each method on each class. That's repetitive but works.

> To be honest, it seems you would have a simpler implementation if you handled the read-only vs. read-write in a single custom decorator that you attach to a `before_request` instead of having two, which in my opinion makes it more confusing.

Yes, it is slightly confusing.

But I'm not sure how to do this in a single decorator and no repeating most of the `login_required` [code](https://github.com/miguelgrinberg/Flask-HTTPAuth/blob/f18fb027cf92bf461040b4d152893c02b9462e94/flask_httpauth.py#L137L159) myself? I would like to filter based on endpoint (resource) and then http method. How would I call the functionality of `login_required` myself because only the decorator is mentioned in the docs. I would (as far as I can see) need to repeat the excerpt from the link above. I do not see what I would need to return in the `before_request` handler to check or signal if I'm authorized to do something.

I can see some advantages from making the functionality public to just check in my code myself if I'm authorized with a given role, ...
Or do I just need to use `current_user()` and check if I found something unexpected? (Not sure what.)

**Comment by miguelgrinberg** [comment]
So this is what I was thinking, more or less:

```python
@bp_api.before_request
@auth.login_required
@filter_by_method
def before_request():
    pass
```

Then in your `filter_by_method` decorator you can check `auth.current_user().role` and compare it against `request.method` to decide if you allow the request or not. I think this is simpler than your implementation wrapping a decorator inside another and using two before request handlers.

**Comment by Querela** [comment]
Your example would be the best case - I would also like it like this. I may have to test some scenarios because I see some issues and I'm not sure if it will work for me like this or that I can implement it easily.

I see two issues(?) with this:
- I need to use the less restrictive role to allow all (i. e. reading for all, `"api-ro"`) and then have to check against the more restricted endpoints/methods (like writes, `"api-rw"`), so the roles have to build on each other (my use case). Can I easily request another http authentation from the user (needs `write` but has `read`?) or is that impossible according to web standards? And not sure how to best signal a permission error as feedback.
-  I can use multiple roles in `auth.login_required` but have to check myself which role is currently used and for which endpoint/method it is allowed. Here it would be more straightforward to just decorate each endpoint/method instead of a central handler?

Both issues are probably not that severe, so I will have to try it out first. Some things are vague and if I can't formulate them here I will need to think about them more.

**Comment by miguelgrinberg** [comment]
Forget the role support in Flask-HTTPAuth. Use the extension for authentication only, then add your role checking with your own decorator. That would be my advice.

**Comment by Querela** [comment]
:-)
Well, I will keep it as is for now. It works for me.
I know there are other (larger) extensions out there with user login, roles, etc. but I only wanted something small and easy to setup and use. This extension more or less perfectly meets my requirements.
And my webapp mentioned in this issue can be simplified to just a single role but I wanted to do it more fine-grained.

_We can close the issue for now and I will try various things slowly._

**Comment by miguelgrinberg** [comment]
Sounds good. Let me know if you have any other questions.
