### ISSUE TITLE
How to protect "hidden" endpoints/routes

### ISSUE THREAD

**Issue by Querela** [miguelgrinberg/Flask-HTTPAuth#107]
How can I protect **arbitrary** routes in my webapp with HTTPAuth?
In particular, using flask-apispec (swagger) I just initialize the extension and optionally provide setting on what the routes are, e. g.:

```python
from flask_httpauth import HTTPBasicAuth
from flask_apispec.extension import FlaskApiSpec
from werkzeug.security import check_password_hash

auth = HTTPBasicAuth()
docs = FlaskApiSpec()

def register_extensions(app):
    # ...

    @auth.verify_password
    def verify_password(username, password):  # pylint: disable=unused-variable
        users = app.config["AUTH_USERS"]
        for user in users:
            if user["name"] != username:
                continue
            if check_password_hash(user["password"], password):
                return user
        return False

    @auth.get_user_roles
    def get_user_roles(user):  # pylint: disable=unused-variable
        return user["roles"]

    # ...

    app.config.update(
        {
            "APISPEC_SPEC": ...,
            "APISPEC_SWAGGER_URL": "/swagger/",
            "APISPEC_SWAGGER_UI_URL": "/swagger-ui/",
        }
    )
    docs.init_app(app)

    # ...
```

Flask-HTTPAuth only provides decorators for me, so how can I protect those routes that are not declared by me? (Besides only enabling the apispec extension in Development/Testing environments.)

**Comment by Querela** [comment]
Mhh... I looked into Flask, maybe this will work:
From https://github.com/pallets/flask/blob/c74f46979a8b8358437bd7f76e478d04248a9c72/flask/app.py#L1075

```python
endpoint = "...". # this should be known (from flask routes ...)
old_func = app.view_functions.get(endpoint)
if old_func is not None:
        auth_func = auth.login_required(old_func)
app.view_functions[endpoint] = view_func
```

I still have to test it.
**And** I'm not sure about the decorator priority/order. Calling the `auth` decorator immediately after the route is determined seems good as no further decorators are called but this may not always be best.

**Comment by miguelgrinberg** [comment]
@Querela What you did is a bit hacky, but should work. An alternative would be to add the decorator to a `before_request` handler.

**Comment by Querela** [comment]
> @Querela What you did is a bit hacky, but should work. 

I know ... but it works really well so far. Just those _possible_ other decorators are an unknown factor.

> An alternative would be to add the decorator to a `before_request` handler.

Well yes, but as far as _I_ know, I can (a) only protect my whole Flask application or (b) a single blueprint? But the extension declares a blueprint itself and makes it not publicly available for other uses.

https://github.com/jmcarp/flask-apispec/blob/975658c37c13aaae9a1b242bf3e2342f0d49d0f0/flask_apispec/extension.py#L75L92

**Comment by miguelgrinberg** [comment]
You seem to always resort to hacking the Flask internals to get what you need. :)

What I was thinking was a custom decorator that uses `request.blueprint` and/or `request.endpoint` to figure out what protection is needed.

**Comment by Querela** [comment]
> You seem to always resort to hacking the Flask internals to get what you need. :)

Mhh ... Not healthy and stable.
But some things can be better understood if you can look how they work. :-)

> What I was thinking was a custom decorator that uses `request.blueprint` and/or `request.endpoint` to figure out what protection is needed.

Well. I could hook into the app handlers and then check. This seems easy.
But how do I call the httpauth machinery? I would like to reuse the automatic authentiation handshakes etc. (401 ...)
Do I just call `auth.auth_error_callback(status)`? [from here](https://github.com/miguelgrinberg/Flask-HTTPAuth/blob/f18fb027cf92bf461040b4d152893c02b9462e94/flask_httpauth.py#L137L159)

**Comment by miguelgrinberg** [comment]
I really don't think I should be giving you advice on this type of solution based on hacking attributes of the Flask object, because I don't really believe in it.

But all I'm going to say is that Flask-HTTPAuth's `login_required` is a decorator, so you call this "machinery" by decorating your function, or by chaining this decorator with your own.

**Comment by Querela** [comment]
Mh. OK.
My issue is just that are part of the application is open for public use and the swagger endpoint should be protected as it allows everything, more or less. But the swagger endpoint is not declared myself so I can't easily decorate it. Decorating the app would block the other public endpoints...
I will search for better approaches.
