### ISSUE TITLE
MultiAuth doesn't support 'optional'

### ISSUE THREAD

**Issue by pryankster** [miguelgrinberg/Flask-HTTPAuth#109]
title says it all ... PR on the way

**Comment by janash** [comment]
Any progress on this?

**Comment by miguelgrinberg** [comment]
The PR isn't passing the build, I cannot merge it until it does.

**Comment by janash** [comment]
The failure on the build #110 seems pretty minor (flake8). I'm actually not sure if it's a problem with the code or something with the check itself: 

```ERROR: InvocationError for command /home/travis/build/miguelgrinberg/Flask-HTTPAuth/.tox/flake8/bin/flake8 '--exclude=.*' --ignore=E402 flask_httpauth.py tests examples (exited with code 1)```

If the check is not having a problem, it seems to be only very minor (line length and missing whitespace after comma).  @pryankster - can you quickly fix?

**Comment by mwri** [comment]
Sorry to butt in @pryankster but I need this! I've committed a wee update to your PR. @miguelgrinberg this passes.

**Comment by mwri** [comment]
Thanks for the quick release @miguelgrinberg appreciate it.

**Comment by miguelgrinberg** [comment]
@mwri No problem. Thanks for helping out with the PR!
