### ISSUE TITLE
how to define decorator for use by multiple modules

### ISSUE THREAD

**Issue by bsl** [miguelgrinberg/Flask-HTTPAuth#111]
Hi, sorry to bother you. I see how to use this in a single module. But now that I've defined my `verify_password` function, how can I use it in multiple places without repeating it? I don't understand the @ notation that actually uses an instance of HTTPBasicAuth. Thanks.

**Comment by miguelgrinberg** [comment]
Just import the `HTTPBasicAuth` object that you created into other files in which you need to use it. The "@" thing is called a decorator, it's a Python feature.

**Comment by bsl** [comment]
Thanks very much.
