### ISSUE TITLE
User enumeration

### ISSUE THREAD

**Issue by HughVolpe** [miguelgrinberg/Flask-HTTPAuth#117]
The simplified example in the docs for a basic auth login only does the password hash check if the user exists. I may be missing something but I think this would allow someone to try out usernames and find ones that are present? I have tried it out and the request time is quite different between request with valid users and invalid (both with invalid passwords).

Happy to suggest a PR if you want?

**Comment by miguelgrinberg** [comment]
Sure, a PR is appreciated.

**Comment by HughVolpe** [comment]
I've raised the PR. Since this issue, I've done a bit more research. It doesn't seem like many people still think this is a security problem. I checked a major framework to see how they handle it, and they don't either! But the OWASP guidelines do say you should prevent user enumeration. It might be reasonable not to merge this if you think it just makes the examples too confusing, without major benefit.
