### ISSUE TITLE
why the Flask view function need authentication even the function did not have @auth.login_required decorators?

### ISSUE THREAD

**Issue by myahuang** [miguelgrinberg/Flask-HTTPAuth#136]
Hi!
My app use HTTPBasicAuth modul,the code is showing as following:

```
@auth.verify_password
def verify_password(username_or_token, password):
    if request.path == "/api/login":
        user = User.query.filter_by(username=username_or_token).first()
        if not user or not user.verify_password(password):
            return False
    else:
        user = User.verify_auth_token(username_or_token)
        if not user:
            return False    
    g.user = user
    return True
```
```
@app.route("/user/info")
@auth.login_required
def userinfo():
    return make_response(jsonify(usertiger), 200)
```
```
@app.route('/', methods = ['GET'])
def getdata():
    return jsonify(random.randint(0,5))
```

When the frontend access router '/user/info', the flask server work fine, but why when the frontend access router '/',the flask server response status code 401,this router don't have @auth.login_required decorators

**Comment by miguelgrinberg** [comment]
Sorry, but I cannot reproduce the problem with my own example code. Please provide the complete application so that I can test it here.

**Comment by myahuang** [comment]
app/_init_.py
`
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_httpauth import HTTPBasicAuth
from flask_cors import CORS

app = Flask(__name__)
CORS(app)
app.config.from_object('config')
db = SQLAlchemy(app)
auth = HTTPBasicAuth()

from . import models, views
`
app/models.py
`
# -*- coding:utf-8 -*-

from app import db, app
from passlib.apps import custom_app_context
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer, SignatureExpired, BadSignature

class User(db.Model):
    __tablename__ =  'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(32), index=True)
    password = db.Column(db.String(128))

    def hash_password(self, password):
        self.password = custom_app_context.encrypt(password)

    def verify_password(self, password):
        return custom_app_context.verify(password, self.password)

    # 获取token，有效时间10min
    def generate_auth_token(self, expiration = 600):
        s = Serializer(app.config['SECRET_KEY'], expires_in = expiration)
        return s.dumps({ 'id': self.id })

    @staticmethod
    def verify_auth_token(token):
        s = Serializer(app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except SignatureExpired:
            return None # valid token, but expired
        except BadSignature:
            return None # invalid token
        user = User.query.get(data['id'])
        return user
`

**Comment by miguelgrinberg** [comment]
I don't see the problem with your code. Here is a request to `/`:

```
$ curl http://localhost:5000/
3
```

And on the server log:

```
getting data
127.0.0.1 - - [26/Sep/2021 19:35:27] "GET / HTTP/1.1" 200 -
```

**Comment by myahuang** [comment]
Thanks for your reply! I try many times, and find it may be IDE problems. The problem can be occur when i use IDE teminal to excute python file. But when i use IDE menu 'run' command, the problem will disappear!
