### ISSUE TITLE
How do I make HTTPDigestAuth not use cookies?

### ISSUE THREAD

**Issue by GormWH** [miguelgrinberg/Flask-HTTPAuth#140]
I'm new to flask and using HTTPAuth to use http digest authentication.
Digest auth works perfectly on browsers but I'm trying to get request without cookies.

From this documentation[https://flask-httpauth.readthedocs.io/en/latest/] I found that using Flask-Session and Flask-KVSession may resolve my problem but how exactly can I change httpauth to use these extensions?

(I'm sorry if my questions are not appropriate. I'm just a noob)

**Comment by miguelgrinberg** [comment]
Flask-HTTPAuth does not use cookies, it uses the user session. To make this usage secure you have to use server-side user sessions. The two extensions given accomplish this. Flask-HTTPAuth does not need to change in any way, you just need to make sure the user session storage is in the server and not  in the cookie as Flask does by default.

**Comment by GormWH** [comment]
Thank you for the comment!
I wasn’t aware of what flask default session is.
