### ISSUE TITLE
Is there any plan to support 'qop' option?

### ISSUE THREAD

**Issue by ballzb** [miguelgrinberg/Flask-HTTPAuth#147]
Hi there,

I need support 'qop=auth' in my app, because 'qop' option is required. 
So I want to know if you have any plan about that.

Thanks.

**Comment by miguelgrinberg** [comment]
I don't have any plans to change or improve digest auth myself, because very few people use it these days. You are welcome to submit a PR with the `qop` support if you'd like it to be included.

**Comment by ballzb** [comment]
OK, I could have a try.

**Comment by ballzb** [comment]
Hi,
I have submit a PR that supporting qop=auth, please help to check.

Thanks.

**Comment by lafrech** [comment]
I think this was achieved (see #148).

**Comment by miguelgrinberg** [comment]
Correct. This issue needs to be closed.
