### ISSUE TITLE
Custom return response on unauthorized

### ISSUE THREAD

**Issue by sicenul** [miguelgrinberg/Flask-HTTPAuth#150]
Hi, I use HTTPBasicAuth, and when unauthorized, it will return "Unauthorized Access" response.
Is it possible to change the response? and please show me how?
for example, I want json response like this:
```
{
    "status": false,
    "code": 401,
    "message": "some message"
}
```
Thank you.

**Comment by miguelgrinberg** [comment]
Use the `error_handler` decorator:

```python
@auth.error_handler
def auth_error(status):
    return {
        "status": False,
        "code": 401,
        "message": "some message"
    }, 401
```

**Comment by sicenul** [comment]
Nice, thanks.
