### ISSUE TITLE
user/pwd encoding is assumed (hardcoded) to be utf-8

### ISSUE THREAD

**Issue by lafrech** [miguelgrinberg/Flask-HTTPAuth#151]
Hi.

First of all, thanks @miguelgrinberg for sharing this lib. We use it to secure our APIs and it works a treat.

We just got caught by an encoding issue today while setting a password containing a `ç`.

Our interface uses requests and requests uses `latin-1` by default to encode user/pwd.

https://github.com/psf/requests/blob/2a6f290bc09324406708a4d404a88a45d848ddf9/requests/auth.py#L56-L60

However, Flask-HTTPAuth assumes `utf-8`:

https://github.com/miguelgrinberg/Flask-HTTPAuth/blob/b42168ed174cde0a9404dbf0b05b5b5c5d6eb46d/src/flask_httpauth.py#L224-L225

There doesn't seem to be a consensus about which encoding to use: https://stackoverflow.com/questions/7242316/what-encoding-should-i-use-for-http-basic-authentication.

From [this discussion](https://github.com/psf/requests/issues/4564), I understand that requests uses `latin-1` for historical reasons and that if a change was to be made, it would have to be in a major version of course, and it would rather be not to assume anything and let the user encode the data himself.

I don't expect Flask-HTTPAuth to change anything at this point. I just thought it might be useful to reach attention on this issue, because this is the kind that tends to occur in production rather than in tests and it can be a bit tricky to debug.

Perhaps Flask-HTTPAuth could expose a parameter or a class attribute to customize the encoding. And/or say a few words about it in the docs.

Honestly I don't know which encoding I would choose if given the choice. It it easy enough for us to modify our UI code to encode the credentials in `utf-8` before passing them to requests so problem solved... until we realize that the OpenAPI frontend we're using (Rapidoc) doesn't seem to use `utf-8` either. I shall open an issue there as well. (Related Swagger-UI discussion: https://github.com/swagger-api/swagger-ui/issues/2456.)

Thanks for reading. Hopefully this message will be helpful to people facing the same issue.

**Comment by miguelgrinberg** [comment]
This is a tricky issue, the Basic Auth standard does not really have a great solution. The current version of the RFC suggests the server explicitly indicates it accepts UTF-8 credentials by adding the `charset` argument to the authentication prompt ([link](https://datatracker.ietf.org/doc/html/rfc7617#section-3)). I'm not doing that, and I think I should.

Beyond that, I guess I could implement a latin-1 decode if the utf-8 one fails. Need to investigate if that is feasible.

**Comment by miguelgrinberg** [comment]
@lafrech Can I ask you to install the main branch of this repo and check if the latin1 credentials are now handled correctly? Thanks!

**Comment by lafrech** [comment]
I meant the server could choose either latin-1 and utf-8 and documented this somewhere (although in a non-standard way). But ultimately, clients wouldn't conform and having the server silently accepting both encoding probably makes everyone's life easier.
