### ISSUE TITLE
Customized 401 page

### ISSUE THREAD

**Issue by lrlrlrlr** [miguelgrinberg/Flask-HTTPAuth#154]
This library is very handy and easy to use.  But when I was trying to add my own 401 pages with the errorhandler, I found that
there is no way to modify the 401 page.

My code:
```
@app.errorhandler(401)  
def custom_401(error):  
    return Response('Customized 401 pages - Hello world!', 401, {'WWW-Authenticate':'Basic realm="Login Required"'})  
```

But it seems the 401 page still remail the original one with plain text **"Unauthorized Access"**.
I have tried the same code for 404 page, it works. But seems **the errorhandler can not affect the 401 page return from Flask-HTTPAuth**.

I have tried to search online and read the doc but there is no similiar question or solution. Does anyone has any idea?

**Comment by lrlrlrlr** [comment]
CentOS 8
Python: 3.6.8
Flask: 2.0.3
Auth method: HTTPDigestAuth

**Comment by miguelgrinberg** [comment]
This extensions uses its own error handlers. See the [documentation](https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPBasicAuth.error_handler) for an example.

**Comment by lrlrlrlr** [comment]
Thanks! Appreciate your prompt reply. Your library and the flask tutorial are really helpful  :)
