### ISSUE TITLE
Restrict endpoint to selected auth in MultiAuth

### ISSUE THREAD

**Issue by tapan1359** [miguelgrinberg/Flask-HTTPAuth#155]
Hello, I am using MultiAuth in my application with Two Token Auths and one Basic Auth. I want to restrict one endpoint to only Two token auths. Is there a way possible to do it using MultiAuth? 

if not is it possible to support it with something like `allowed_auth` parameter?
```
class MultiAuth(object):
    def login_required(self, f=None, role=None, optional=None, allowed_auth=[]):
```

route will be like
```
@app.route("/example", methods=["GET"])
@auth.login_required(allowed_auth=["Basic"])
def example_route() -> Any:
```

**Comment by miguelgrinberg** [comment]
Have you considered creating two `MultiAuth` objects, once with all your auth schemes and a second one with just the two that you need on this one endpoint? There is no requirement to have a single auth object, you can create as many as you need to allow for variations across endpoints.
