### ISSUE TITLE
Role based authentication for MultiAuth

### ISSUE THREAD

**Issue by algeti** [miguelgrinberg/Flask-HTTPAuth#156]
Following the documentation in order to use HttpAuth for web and token authentications, we have option to use MultiAuth
```
from flask_httpauth import HTTPBasicAuth, HTTPTokenAuth, MultiAuth
basic_auth = HTTPBasicAuth()
token_auth = HTTPTokenAuth(scheme='Bearer')
auth = MultiAuth(basic_auth, token_auth)
```
This works fine, however, when it comes to the role based authentication we have to create function for database model:

```
from ..utils.extensions import db, ma, basic_auth, token_auth, auth

 @token_auth.get_user_roles
    def get_user_roles(user):
        return user.get_roles()
```
If I put the auth(MultiAuth) then it gives warrning that get_user_roles doesn't exist for MultiAuth. So, either we need to put basic_auth or token_auth which means that we can not use role based authentication for both.
Kindly, advise how can I use role based for web/token authentications

**Comment by miguelgrinberg** [comment]
Doesn't this work?

```python
@basic_auth.get_user_roles
@token_auth.get_user_roles
def get_user_roles(user):
    return user.get_roles()
```

**Comment by algeti** [comment]
Thanks Miguel!
Recommended approach worked well.
