### ISSUE TITLE
Fix documentation on import

### ISSUE THREAD

**Issue by lepture** [miguelgrinberg/Flask-HTTPAuth#18]
https://github.com/mitsuhiko/flask/issues/1135

Use `from flask_foo import bar` instead of `from flask.ext.foo import bar`.

**Comment by miguelgrinberg** [comment]
Yes, need to update it.

**Comment by Aayush-Kasurde** [comment]
Fixed using [PR 19](https://github.com/miguelgrinberg/Flask-HTTPAuth/pull/19). @miguelgrinberg  Could you please close this issue ?
