### ISSUE TITLE
Best way of manually triggering auth.login_required

### ISSUE THREAD

**Issue by melonista** [miguelgrinberg/Flask-HTTPAuth#20]
Hi, 

Thanks for this library!

I have a route that users call in order to get objects (/api/get_object). The issue is that some objects are public while others are private. Therefore, I want to return forbidden if the user is not logged in and asks for a private object. Only logged in users can get private objects (in reality only the owner of the object can get it, but I omitted this to keep the example as simple as possible). What is the best way of doing this?

I was thinking in two options:

1- Make a public and a private route: /api/get_object and /api/get_object_private.
When the user request a private object, the request is redirected to /api/get_object_private, which has the @auth.login_required decorator. This is not a very elegant solution because I have to duplicate all the routes where this kind of stuff happens.

2- To have only one route, and in case the requested object is private, to check if "g.user" is defined and return forbidden if it is not (although I am not sure about the security of this option or how to check if g.user is defined)

But I was thinking that maybe there is just a way of calling auth.login_required within the function of the route. Is it?

Thank you!

**Comment by miguelgrinberg** [comment]
I think you can do it as follows:

- Protect your route with the `login_required` decorator as if you only wanted to work with authenticated users.
- In the `verify_password` callback function, check if `username == ''`. This will be `True` when a user tries to access the route without sending authentication credentials. If this is the case, set `g.authenticated = False` and then return `True` to allow the route to run.
- If `username != ''` then check password. If it is valid, set `g.authenticated = True` and then return `True. Else return `False`.
- In your route function, before you return a protected resource check `g.authenticated`. If it is `False`, then call `abort(401)` or your own custom error function for unauthorized user.

With the above implementation this is how things work:

- if the user sends valid username and password, then there is full access to everything.
- If the user sends invalid username and password, then a 401 error is return and there is no access to anything.
- If the user does not send authentication, then only public resources are accessible, everything else return 401.

Does this work for you?

**Comment by melonista** [comment]
Great, thanks!
