### ISSUE TITLE
The @auth.login_required() must be always after @route

### ISSUE THREAD

**Issue by somenxavier** [miguelgrinberg/Flask-HTTPAuth#25]
Please, warn that in the [documentation](http://flask-httpauth.readthedocs.org/en/latest/), please. I got crazy with that ;-)

```
@app.route("/api/user/", methods=['GET'])
@auth.login_required
def get_users():
	bla....

```
will return good response. But 

```
@auth.login_required
@app.route("/api/user/", methods=['GET'])
def get_users():
	bla....

```

has no effects.

**Comment by miguelgrinberg** [comment]
Decorators cannot be freely reorder, that is correct. The route decorator has to be the first, as that makes sure all other decorators are included in the route declaration. All examples in the documentation show the decorator after the route, and this is not only true for this extension for pretty much all extensions.

**Comment by somenxavier** [comment]
You have to know that ;-)
I suggest that you put a warning in the documentation. It could be useful for newbees like me.
On the other hand, in the README of github you still have the old documentation link instead of readthedocs.

Thanks,

**Comment by yazhuo-wyze** [comment]
这个问题把我搞疯了。
