### ISSUE TITLE
Digest auth

### ISSUE THREAD

**Issue by Aidenir** [miguelgrinberg/Flask-HTTPAuth#26]
Hey, sorry if this is dumb, but I am pulling my hair out over issues with digest auth and this library.
I copied the example from the readme, and just added host='0.0.0.0' to the app.run to access it from my desktop (running on server). I brought up the url i chrome, tried logging in as john with password hello. First time it worked. Then I tried in an incognito tab, and I only get 401s after that. Tried with 

curl -v --digest -u "john:hello" host:5000/

Get 401 there as well. Is there some special trick I'm missing for digest auth?

**Comment by gensmusic** [comment]
you need a cookie
try this
curl -v --digest -u "john:hello"  localhost:5000/ -c ./mycookie

**Comment by miguelgrinberg** [comment]
Yes. As explained in the documentation, the digest implementation by default uses the Flask session, so you need cookies. Not only that, to make the process secure you need to use server-side sessions.
