### ISSUE TITLE
Security hole: HTTP Digest Auth implementation relies on cookies for nonce/opaque verification

### ISSUE THREAD

**Issue by proycon** [miguelgrinberg/Flask-HTTPAuth#27]
Correct me if I'm wrong, but since flask.session uses cookies and HTTPDigestAuth uses sessions
to hold the nonce, the client-supplied nonce from the authentication header is simply checked against another client-supplied nonce (from the cookie), making it insecure. An attacker sniffing the network can always forge a cookie and so duplicate the same nonce. The same goes for the opaque for that matter. I think the nonce/opaque to check against should be retained fully server-side.

**Comment by miguelgrinberg** [comment]
Yes, using cookies to store the nonce and opaque hashes is far from ideal. I thought I had a note regarding that in the documentation, but it does not look like that ever got added. When working with digest auth it is required to use server-side sessions, such as those provided by the Flask-Session or Flask-KVSession extensions.

**Comment by miguelgrinberg** [comment]
@proycon I have added appropriate documentation here: http://flask-httpauth.readthedocs.org/en/latest/#security-concerns-with-digest-authentication. Please let me know if you think there are any holes when you follow these recommendations.

I thought I've done this long ago, sorry for any confusion this may have caused.

**Comment by proycon** [comment]
Looks good! I did my own little custom nonce memory implementation in the commit I referenced here.
