### ISSUE TITLE
http auth with nginx and uwsgi

### ISSUE THREAD

**Issue by gensmusic** [miguelgrinberg/Flask-HTTPAuth#29]
Recently I use flask + uwsgi + nginx to make a server and I use Flask-HTTPAuth
to do the digest auth in flask.
Most ot time it works fine but when I do a large post (let's say 3M) then I got 502 error in browser.
nginx error:

 [error] 3438#0: *16 sendfile() failed (32: Broken pipe) while sending request to upstream, client: 203.100.xx.xx, server: xxxx.net, request: "POST /create_invitation HTTP/1.1", upstream: "uwsgi://unix:/xxxxr/uwsgi.sock:

I search a lot on google to solve it but didn't success until I close the http auth.
And it works well now. So should I move http auth from flask to nginx ?

I guess flask-httpauth close the connection after it sends 401 ? So nginx got error ?

thanks

**Comment by gensmusic** [comment]
And also a lot of this errors:

2015/10/30 04:29:20 [error] 4021#0: *129 readv() failed (104: Connection reset by peer) while reading upstream, client: 203.100.xx.xx, server: tplgy.net, request: "POST /create_invitation HTTP/1.1", upstream: "uwsgi://127.0.0.1:3031"

**Comment by miguelgrinberg** [comment]
Are there any errors, crashes or stack traces printed by the Flask process?

**Comment by gensmusic** [comment]
No. nothing. Flask is normal. Uwsgi is normal too. I can see flask return a 401 to client from uwsgi log.
But client ends up no response. Some answers in google says it's maybe because uwsgi or flask close the connection before it reads the post body, therefore nginx can't read from uwsgi. I just want to know if http-auth will cause this situation. I use http-auth digest in app_before_request for every request.

**Comment by gensmusic** [comment]
I think I found the issue. We are using Alomofire to send http request. And there is no header "connection:keep-alive". After we add this header, it works now.
I think the reason might be:
app -> post -> nginx ->uwsgi->http-auth
                                          return 401, no keep-alive, close connection
                       error, read from uwsgi
Maybe nginx is keepiing alive but flask or uwsgi just close the connection because there is no keep-alive header.
