### ISSUE TITLE
The package's metadata doesn't specify python3 support

### ISSUE THREAD

**Issue by eli-b** [miguelgrinberg/Flask-HTTPAuth#32]
Issue [2](https://github.com/miguelgrinberg/Flask-HTTPAuth/issues/2) makes it seem that python3 is supported. To signal that this package supports python3, please add the following line to the classifiers in the package's metadata: "Programming Language :: Python :: 3".

Flask-HTTPAuth is one of the last packages blocking my move to python3, so if formalities are the only problem here that would be wonderful!

**Comment by miguelgrinberg** [comment]
Fixed. Version 2.7.2 has a Python 3 classifier.

**Comment by eli-b** [comment]
Thanks a lot!
