### ISSUE TITLE
HTTPBasicAuth with custom scheme

### ISSUE THREAD

**Issue by Lestt** [miguelgrinberg/Flask-HTTPAuth#37]
Hi,
Maybe i did something wrong, but i try to use HTTPBasicAuth with custom scheme and i am not able to get it work.
In my python script, i have:

`from flask.ext.httpauth import HTTPBasicAuth`
`auth = HTTPBasicAuth("FooBar")`

Client-Side, The header's Authorization line is the concatenation of scheme and Base64 coded of username:password string:
`Authorization:FooBar cXNkcXNkcWQ6ZHNmZGZkZnM=`

When the @auth.verify_password function is called, the two parameters are empty (NoneType). But if i set the scheme with default scheme('Basic'), these parameters are good.

Did i miss something ?

**Comment by miguelgrinberg** [comment]
Yes. When I wrote this code long ago I wanted to offer support for alternative schemes, but what I did not realize at the time, is that Werkzeug's parsing of the `Authorization` header only works for basic and digest auth.

In recent times, I create a different class called `HTTPTokenAuth` that you can use for custom authentication schemes. When using this class I do my own parsing, and pass the credentials as a token, which your callback function can decode and interpret as appropriate for your application.

**Comment by Lestt** [comment]
Ok thanks for the fast reply, ill try it tomorrow.

**Comment by Lestt** [comment]
Well maybe my reflexion is bad. I would like to use the HTTPBasicAuth for the authentification (when user provide login/password), then my server sends him back a token and the client should provide the token for each next calls

So in my program i used first HTTPBasicAuth for the login section, and then i have to use HTTPTokenAuth to protect all other calls.

Is that possible to have the two classes used in the same program ? Did i misunderstand something ?

**Comment by miguelgrinberg** [comment]
@Lestt absolutely. You can use two or more classes that provide different authentication methods, and then protect each endpoint with the appropriate one. There is also `HTTPMultiAuth`, which allows you to combine multiple auth classes into one, so that you can have alternative methods in a single endpoint. Here is an example that uses basic, token and multi auth: https://github.com/miguelgrinberg/Flask-HTTPAuth/blob/master/examples/multi_auth.py

**Comment by Lestt** [comment]
Great ! Thanks for your support :)
