### ISSUE TITLE
passing token, bad signature

### ISSUE THREAD

**Issue by tharrington** [miguelgrinberg/Flask-HTTPAuth#40]
I must be missing something obvious. I create a user and send back and auth token. After that I am using postman to access a protected route with that auth token, but the token is null. Here is some code:

Create the user:
```
@api.route('/users', methods=['POST'])
def create_user():
	print('create user')
	user = User(email='tyler@test.com', password='test')
	if(user.validate_email()) :
		db.session.add(user)
		db.session.commit()
		return jsonify({ 'user': user.to_json(), 'token' : user.generate_auth_token(3600) })
	return jsonify({'error': 'email already taken' })
```

user model:
```
def generate_auth_token(self, expiration=600):
		s = Serializer(current_app.config['SECRET_KEY'], expires_in=expiration)
		return s.dumps({'id': self.id}).decode('utf-8')
```

protected route:

```
@api.route('/users', methods=['GET'])
@auth_token.login_required
def get_users():
	users = User.query.all()
	return jsonify({'users': [user.to_json() for user in users] })
```

Verify token method on user model: This is where I get nothing in the token print and ultimately a bad signature

```
@staticmethod
	def verify_auth_token(token):
		print('### verifying')
		print(token)
		s = Serializer(current_app.config['SECRET_KEY'])
		try:
			data = s.loads(token)
		except SignatureExpired:
			print('### expired')
			return None    
		except BadSignature:
			print('### bad signature')
			return None   
		user = User.query.get(data['id'])
		return user

```

I guess I'm a bit confused on how this works. the HTTPBasicAuth() object has a decorator method called login_required which always hits the verify_auth_method on the object? Can you please explain this?

Finally, my auth token is sent in a header : 

{ Content-Type: application/json, Authorization : myToken}

**Comment by miguelgrinberg** [comment]
Your "Authorization" header is missing the auth scheme. If you are using `HTTPTokenAuth` and are not specifying a custom scheme, then the scheme name is "Bearer". The header should then be:

    Authorization: Bearer myToken

**Comment by tharrington** [comment]
Awesome, I just didn't have the scheme correct. Do you typically implement both token and basic? Once a user authenticates via password, switch to token based auth?

**Comment by miguelgrinberg** [comment]
Yeah, that is one of the most common patterns, you protect the "get token" endpoint with basic auth, and everything else with token auth.

**Comment by tharrington** [comment]
Thanks!
