### ISSUE TITLE
What should I send to token-verified url?

### ISSUE THREAD

**Issue by TaylorHere** [miguelgrinberg/Flask-HTTPAuth#41]
I try to use curl to debug my app , 
I use this command to my URL with token_verify based on 
`curl -H "Authorization token:eyJhbGciOiJIUzI1NiIsImV4cCI6MTQ2NDA1NTg2OSwiaWF0IjoxNDY0MDU1MjY5fQ.eyJpZCI6bnVsbH0.4Oe60fyM8t6BvPvdZWlNqCO3ZKXW5HHsjVmoaUkp-1E" http://127.0.0.1:5000/app/star/0
`
I'm sure of the token and url is true, but when I'm debug ,I find that @token_auth.verify_token function receive an None token,so How to send a token when I using  HTTPTokenAuth

**Comment by miguelgrinberg** [comment]
The format of the Authorization header is wrong. Here is what you should send:

    Authorization: <scheme> <credentials>

Examples:

    Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l
    Authorization: Token eyJhbGciOiJIUzI1NiIsImV4cCI6MTQ2NDA1NTg2OSwiaWF0IjoxNDY0MDU1MjY5fQ.eyJpZCI6bnVsbH0.4Oe60fyM8t6BvPvdZWlNqCO3ZKXW5HHsjVmoaUkp-1E

**Comment by TaylorHere** [comment]
I use this command to debug ,But I still got None token 
curl -H "Authorization: Token eyJhbGciOiJIUzI1NiIsImV4cCI6MTQ2NDA1NTg2OSwiaWF0IjoxNDY0MDU1H0.4Oe60fyM8t6BvPvdZWlNqCO3ZKXW5HHsjVmoaUkpE" "http://127.0.0.1:5000/app/star/0"

**Comment by miguelgrinberg** [comment]
What is the scheme that you are using? Are you using "Token"? That was my example, the scheme needs to match what you are using. That should be "Basic" if you are using basic auth. If you are using the new token support and did not set your own scheme, then the default is "Bearer".

**Comment by TaylorHere** [comment]
I'm using HTTPTokenAuth scheme ,how to set scheme?

**Comment by miguelgrinberg** [comment]
The scheme is passed as an argument to the HTTPTokenAuth constructor. See http://flask-httpauth.readthedocs.io/en/latest/#token-authentication-scheme-example for an example that uses "Token".

**Comment by TaylorHere** [comment]
Ok,I ignore that，I have got the token, THANK YOU.
