### ISSUE TITLE
auth mechanism in separate file

### ISSUE THREAD

**Issue by trondhindenes** [miguelgrinberg/Flask-HTTPAuth#43]
I'm refactoring some code, and having problems getting flask-httpauth to work when everything's not in the same file.

in my flask app I have my __init__ where imports live, and I've tried putting my verify_password def here.
I have one file/class per route, and I'm having a hard time understanding how to wire everything up.

An example based on a more real-life setup would be super-helpful.
Here's my code atm:
https://github.com/trondhindenes/flansible/tree/e51201b3f89cab90c9d704c6d4050e27febfeaef

**Comment by miguelgrinberg** [comment]
Since the `HTTPBasicAuth` object does not require an application instance to be initialized, it can really go anywhere. What is the problem that you are having? I assume you have circular dependencies?

**Comment by trondhindenes** [comment]
Thanks for responding quickly. I think my problem was that I had an explicit import if HttpBasicAuth in each route class file. Once I removed that, everything started humming along.
