### ISSUE TITLE
License mismatch (BSD vs MIT)

### ISSUE THREAD

**Issue by synapticarbors** [miguelgrinberg/Flask-HTTPAuth#44]
The license included in the repo and specified in `setup.py` is the MIT license but in the `classifiers` section of `setup.py` it says BSD as it also does in `flask_httpauth.py`

**Comment by miguelgrinberg** [comment]
Fixed in release 3.2.0. Now it's all unified on MIT.

**Comment by synapticarbors** [comment]
Thanks Miguel. I've added a [conda](http://conda.pydata.org/) recipe for flask-httpauth on [conda-forge](https://conda-forge.github.io/), so pending approval of the recipe, the library will be available to conda users through the conda-forge channel. I'm happy to be the maintainer of that, but if you're interested in being added as a co-maintainer, please let me know. This would give you commit rights to the recipe once it's accepted.
