### ISSUE TITLE
Multi auth error - need more than 1 value to unpack

### ISSUE THREAD

**Issue by jm66** [miguelgrinberg/Flask-HTTPAuth#51]
Using MultiAuth (basic+token) and I'm getting an error when not providing a **scheme** in the `Authorization` header. 

For instance a `http :5000/api/ "Authorization: $TK"` will throw a `500` error:
```
scheme, creds = request.headers['Authorization'].split(None, 1)
ValueError: need more than 1 value to unpack
```

Using try-catch to bypass the exception might be one quick solution. Thoughts?

**Comment by miguelgrinberg** [comment]
The scheme field is required, you cannot omit it.

I can address this, but the correct way to do it is by returning a 400 error, since the header missing the scheme is malformed.

**Comment by jm66** [comment]
Understood. Thanks.
