### ISSUE TITLE
Disable http auth when testing

### ISSUE THREAD

**Issue by jxltom** [miguelgrinberg/Flask-HTTPAuth#59]
It would be nice to disable http basic auth when set ```flask.app.test``` as ```True```

**Comment by miguelgrinberg** [comment]
Have you considered doing this in your `verify_password()` callback function?

```python
@basic_auth.verify_password
def verify_password(username, password):
    if current_app.config['TESTING']:
        return True
    # ...
```

**Comment by jxltom** [comment]
Oh yes, I can implement it by myself. Thanks, I just realize it now.

**Comment by espoirMur** [comment]
This is awesome ;, Thanks

**Comment by alexvaa** [comment]
it help me, thank you
