### ISSUE TITLE
Can I access the params passed into verify_password?

### ISSUE THREAD

**Issue by sarimabbas** [miguelgrinberg/Flask-HTTPAuth#60]
After passing basic authentication in verify password, is it possible to retrieve the user param within a put/get function so that I can check if it has relevant permissions in my database? (thereby altering the data that is returned). One way seems to be creating different auth objects and callbacks, but this could get messy.

**Comment by miguelgrinberg** [comment]
You can use `auth.username()` to get the user that was authenticated. Alternatively, you can write anything you want to have access to from your view function in the `g` object. For example, in your verify_password function you can write `g.user = <your user object>`, and then you will be able to reference `g.user` later.

**Comment by sarimabbas** [comment]
Thank you very much!
