### ISSUE TITLE
How do I get the problem with the authentication process?

### ISSUE THREAD

**Issue by brunoais** [miguelgrinberg/Flask-HTTPAuth#61]
A failure in the authentication process can be:

- No Authorization header given
- Wrong scheme given
- Wrong or missing header data
- Wrong or not given nonce, opaque, etc... (for HTTPDigestAuth)

Although in production there is not that much gain distinguishing them, in development, much more in quality environment it is good to know and log exactly what is happening inside the application and, when an authorization fails, to know what was the cause.
As it is now, the developer that uses this can only know if the login has failed or succeeded or if there was a problem somewhere between the headers parsing and developer's code.

In my situation, I need to have two programs communicating between each other where I have control over my program but no control over the program that uses this. And so, currently, with it failing, I have no idea if the other program is not sending Authorization, if it is not sending the right scheme in the authorization or if it is sending an empty token (I'm using HTTPTokenAuth).

There are solutions such as logging the Authorization header for a human to read but I really rather just have it done automatically in the response (AKA avoid wasting time with e-mails back and forward).

Any suggestions?

**Comment by miguelgrinberg** [comment]
What prevents you from analyzing and /or logging the `Authorization` header in the `verify_password` or error handler callbacks?

**Comment by brunoais** [comment]
Although I can log the `Authorization` header in one of the callbacks, I still cannot programmatically know what went wrong without redoing your code.

The cause of the mistake can easily be the fault of a proxy which may be modifying the request, a mishandle of a library or a framework (from who is consuming my endpoint).
The idea is to be able to respond back on what was wrong in the entity of the response.
Was the header not sent? Was there a mistake in the scheme? Was the token empty?
Currently, with the `HTTPTokenAuth` authentication, I can't distinguish those programmatically without re-implementing the code myself.
Makes sense?

**Comment by miguelgrinberg** [comment]
I'm not really sure I understand what you are after, but in any case, the logic that you would be re-implementing if you were to do this is fairly simple. We are not talking about a complex decision tree, you just need to answer the following questions:

- Is there an `Authorization` header?
- If yes, is the format of the header correct (i.e. is there a scheme and a token)?
- If yes, is the scheme the expected one?
- If yes, are the credentials correct?

Specifically for token auth, this logic is implemented in just a handful of lines (https://github.com/miguelgrinberg/Flask-HTTPAuth/blob/master/flask_httpauth.py#L65-L77) plus the code that you provide in the verify_token handler.

If you find a way to expand the code to handle these without affecting regular users I'm open to consider it, but my opinion is that adding separate error paths for each of these conditions will make the code for this extension larger and less efficient, all for something that 99.9% if the users are not going to care.
