### ISSUE TITLE
In security context, examples in documentation are terrible

### ISSUE THREAD

**Issue by thugcee** [miguelgrinberg/Flask-HTTPAuth#80]
I got interested in Flask-HTTPAuth so I've started reading its documentation and this is what I can see in examples: clear text passwords, MD5 and SHA. It gives a bad first impression or even sheds a bad light on the framework (like nobody cares about security here). I can understand that there is `get_password` callback for those who want to play with authorization on their laptops, but in my opinion `hash_password` should be deprecated and example for `verify_password` should use BCrypt or something like that.

**Comment by miguelgrinberg** [comment]
I agree, this extension started as a very simple (too simple) attempt to check passwords, and grew into a more complete and secure solution later on. Today, using anything other than the `verify_password`/`verify_token` callbacks is really not a good idea, and the examples in the documentation do not reflect that. I think any examples should use these newer callbacks, the others should be left there for legacy users but not promoted anymore.

Would you be interested in updating the docs to reflect that, or is pointing out the problem as far as you'd like to go?

**Comment by thugcee** [comment]
I'll try to update the docs :)

**Comment by miguelgrinberg** [comment]
Instead of having to make excuses for poor examples in the docs, I have replaced the example with much better ones.
