### ISSUE TITLE
How should I send the request from front-end?

### ISSUE THREAD

**Issue by wizounovziki** [miguelgrinberg/Flask-HTTPAuth#84]
Hi Miguel,
Thanks for sharing.
But I got some trouble when I try to send request to those login_required route with my react front-end.
my headers is written as :
                                               fetch("http://localhost:5000/resource",{
                                                  method:'get',
                                                  headers:{'Content-Type':'application/json',
                                                  'Authorization': 'Token' + token,
                                                  }
                                                })
Also I searched and  tried many other property names like "token","Authorization" etc.
So how should I deal with the request format?The back-end part is almost the same as yours.
Thanks a lot.

**Comment by miguelgrinberg** [comment]
Did you add a space between the word `Token` and the token? Your code above does not appear to have the space.

**Comment by wizounovziki** [comment]
> Did you add a space between the word `Token` and the token? Your code above does not appear to have the space.

Thanks for the mention.I missed the space and the key word should be 'Basic'.

In addition,token should be like this:
token = btoa(username+':'+password);
In the header it has to strictly follow this format,I also forgot this.

**Comment by miguelgrinberg** [comment]
"Basic" is just one of the possible formats. There are others.
