### ISSUE TITLE
use auth within multiple blueprints

### ISSUE THREAD

**Issue by inkrement** [miguelgrinberg/Flask-HTTPAuth#9]
How can a single HTTPAuth setup used within multipe blueprints? I tried to configure it within the **init**.py of my package and import it within my subpackages. But this is a circular dependency. 

`__init__.py` imports blueprint `xy.py`, which itself imports **init**.py, because of auth.

**Comment by joostalbers** [comment]
Hi Inkrement. i am need of the same solution but to be fair i am somewhat of a newbie following a dozen tuts and essentially just clueless. 

can you post the most simplified example of how you achieved this solution.

my blueprints init is just an empty file. i have an auth blueprint which does what i want as long as i talk to the server/auth/whatever route..    but when i add @auth.login_required in one of my other blueprints i really want it to talk to the auth blueprint but it does not, i think you nailed it from the description and some pointers would be awesome.
thanks

**Comment by miguelgrinberg** [comment]
@joostalbers you may want to look at [Flasky](https://github.com/miguelgrinberg/flasky), the application featured in my book. In this application there is an `auth` blueprint that provides auth services to the other blueprints.

**Comment by joostalbers** [comment]
Thanks for the quick response Miguel i'll have a look straight away.

**Comment by inkrement** [comment]
Hi @joostalbers, I don't use flask anymore and therefore my knowledge is quite limited. I published my old source code on github (https://github.com/inkrement/server) maybe it's helpful.
