### ISSUE TITLE
Add login_optional decorator

### ISSUE THREAD

**Issue by smmalmansoori** [miguelgrinberg/Flask-HTTPAuth#90]
Having a ~~`login_accepted`~~ `login_optional` decorator in the `HTTPAuth` class would help build endpoints where authentication is optional as opposed to `login_required` (for example to add extra data when authenticated).

I'm aware of issue #17 which led to providing a workaround using `verify_password` in the `HTTPBasicAuth` class but that only works for basic auth and would lead to adding `basic_auth.login_required` which communicates the wrong intent.

It can be implemented with something like this:
```python
class HTTPAuth(object):
    # ...

    def login_optional(self, f):
        @wraps(f)
        def decorated(*args, **kwargs):
            auth = self.get_auth()

            # Flask normally handles OPTIONS requests on its own, but in the
            # case it is configured to forward those to the application, we
            # need to ignore authentication headers and let the request through
            # to avoid unwanted interactions with CORS.
            if request.method != 'OPTIONS':  # pragma: no cover
                password = self.get_auth_password(auth)
                self.authenticate(auth, password)

            return f(*args, **kwargs)
        return decorated
```

- In this decorator I don't think there is need to worry about connection resets brought up by issue #38 since the function at the route would be running anyways
- I think this should work for both `HTTPBasicAuth` and `HTTPTokenAuth` but don't know about `HTTPDigestAuth` since I don't use it

I use this already by inheriting `HTTPTokenAuth` and adding the decorator, but thought I'd share it in case there is interest in adding it to the library or sharing the pattern in the documentation.

**Comment by miguelgrinberg** [comment]
I would call it `login_optional` to make the intent even more clear, but yes, I'm okay with this idea. Would you like to have a go at it and send a PR?

**Comment by smmalmansoori** [comment]
Sure, I'll give it a try
