### ISSUE TITLE
Does the wheel not support HTTP DIgest in RFC 2617 protocol?

### ISSUE THREAD

**Issue by chen-zhuohan** [miguelgrinberg/Flask-HTTPAuth#92]
I can't find where to choose qop's value. It seems like that it only supports HTTP DIgest in RFC 2069 protocol

**Comment by miguelgrinberg** [comment]
Correct. The `qop` value is currently not implemented, since it is optional.

**Comment by chen-zhuohan** [comment]
Thanks
