### ISSUE TITLE
How to return more information from verify_token

### ISSUE THREAD

**Issue by bshetti** [miguelgrinberg/Flask-HTTPAuth#93]
When using verify_token(token)
seems like I can return False or True.
If I return False then I get "Unauthorized Access"
How do I modify this to return more information?
i.e. "Unauthorized Access - due to bad token format" 
etc?

**Comment by miguelgrinberg** [comment]
You can define your own error handler. See https://flask-httpauth.readthedocs.io/en/latest/#flask_httpauth.HTTPBasicAuth.error_handler.

**Comment by bshetti** [comment]
Thanks so - how do I pass it different values from verify_token
i.e. "Bad token value" when we return False
  or "Token expired" when we return False

**Comment by miguelgrinberg** [comment]
Maybe store the error message in `flask.g` and pick it up in the error handler function?
