### ISSUE TITLE
Add functionality to accept other header names

### ISSUE THREAD

**Issue by pangolingo** [miguelgrinberg/Flask-HTTPAuth#96]
I recently did some work where I needed to accept both an API key and a token with HTTPAuth.
I ended up subclassing `HTTPTokenAuth` to look for the API key on a header called `X-API-Key` (`X-API-KEY: my_api_key`).

It would be cool if this library supported other header names besides just an `Authorization` header for tokens.

My code ended up looking something like this:

```python
class HTTPAPIKeyAuth(HTTPTokenAuth):
    """
    Extension of the HTTPTokenAuth class to allow sending a header like
    "X-API-KEY: my_api_key"
    It doesn't use the "Authorization" header name and doesn't use a scheme type
    """
    def __init__(self):
        super(HTTPAPIKeyAuth, self).__init__(None, None)
        self.verify_token_callback = None

    def get_auth(self):
        if 'X-API-Key' in request.headers:
            return Authorization('api_key', {'token': request.headers['X-API-Key']})
        return None

apiKeyAuth = HTTPAPIKeyAuth()
```

**Comment by miguelgrinberg** [comment]
This was added in https://github.com/miguelgrinberg/Flask-HTTPAuth/commit/575b46ade7188152e1b82de84be949bf3f8a300b.
